coslr: false
criterions:
  PerformanceLoss:
    def_file: ./loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
model:
  clip:
    optim_params: {lr: 0.00001, momentum: 0.9, weight_decay: 0.0005}
    params: {visual_backbone: 'RN50'}
  adapter:
    optim_params: {lr: 0.2, momentum: 0.9, weight_decay: 0.0005}
    params: {feat_dim: 1024}
  fusion:
    optim_params: {lr: 0.02, momentum: 0.9, weight_decay: 0.0005}
    params: {in_dim: 1024, out_dim: 1000}
shuffle: true

dataset_variant: ""

optimizer_variant: "LBFGS"
optimizer_args: {history_size: 5, max_iter: 4}

train_variant: 0
training_opt:

  variation: "image_plus_text" # This determines the rule for combining the text and images
  image_emb_weight: 1

  text_encoder_frozen: true
  image_encoder_frozen: true

  batch_size: 512
  dataset: ImageNet_LT
  dataloader: "paired"
  display_step: 10
  feature_dim: 1024
  num_classes: 1000
  num_epochs: 100
  num_workers: 12
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 3}
